# Generated by Django 4.2.20 on 2025-04-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(choices=[('Admin', 'Admin'), ('Receptionist', 'Receptionist'), ('Doctor', 'Doctor'), ('Lab Technician', 'Lab Technician'), ('Pharmacist', 'Pharmacist')], max_length=50, unique=True)),
            ],
        ),
    ]
