# Generated by Django 4.2.20 on 2025-04-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_app', '0004_appointment_labtest_medicine_prescription_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital_management_app.token'),
        ),
    ]
